<?php
declare(strict_types=1);

namespace App\Controllers;

use Phalcon\Tag;

class IndexController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        Tag::setTitle('Home');
    }

    public function indexAction()
    {

    }

}

